name: handclash
description: A real-time rock paper scissors game.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  socket_io_client: ^2.0.3
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  device_info_plus: ^11.3.3
  flutter_svg: ^2.0.7
  vibration: ^1.8.4
  audioplayers: ^5.2.1
  lottie: ^2.7.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/translations/
    - assets/card/green/
    - assets/card/red/
    - assets/card/joker/
